= SAE 2.02 - Rapport de comparaison d'approches algorithmiques
:toc:
:sectnums:

Réalisé par *Tilian HURÉ (4A)*


{empty} +

[NOTE]
[.text-justify]
Les fichiers ont été renommés afin d'enlever le caractère ``-`` qui posait problème lors de l'importation des fichiers dans certains codes d'analyse.

*NOTATION*
|===
|*Cas*|*Points*
|Ne compile/s'exécute pas|0
|Ne passe pas les tests fournis ou rate certains cas|1
|Meilleur algo de la catégorie|5
|2nd algo|4
|3e algo|3
|4e algo|2
|===
En cas d'ex-aequo, même note. (5/5/3/2 par exemple).



== Catégorie SIMPLICITÉ

=== Simplicité n°29 (java)

*NOTATION*
|===
|*5* points|*_Meilleur algorithme* de la catégorie (le plus rapide et passant tous les tests)._ *TODO*
|===

[.text-justify]
Cet algorithme présente une efficacité satisfaisante en traitant tous les cas, avec des temps d'exécution rapides et une complexité qualifiable de linéaire. *TODO*


==== Prérequis
[.text-justify]
Vérifier la présence du fichier ``simplicite54.java`` dans le répertoire ``~/src/analyse/solutions``. +
 +

[.text-justify]
Remplacer la ligne n°7 du fichier ``EraserTest.java`` (celle avec le commentaire "replace this line") du répertoire ``~/src/test/java`` par le code suivant : +

[SOURCE, java]
----
import analyse.solutions.simplicite54;
----

[.text-justify]
Et remplacer toutes les notations ``Eraser`` du fichier par ``simplicite54``.

[.text-jutify]
Ce programme permet de vérifier que le programme traite bien tous les cas donnés.


==== Reproductibilité
[.text-justify]
Lancer le code de ``EraserTest.java``et vérifier que le programme traite tous les cas donnés.


==== Analyse de la simplicité
[.text-justify]
La simplicité d'un programme peut se déduire à partir de sa lisibilité/compréhension qui sera évaluée subjectivement pour ce rapport, et de sa qualité qui sera évaluée avec l'outil en ligne 'Codacy'. Il reste tout de même nécessaire de vérifier si le programme répond bien à sa tâche en traitant tous les cas pour les chaînes de caractères données.

===== Tests
[.text-justify]
[green]#*Ce programme passe tous les tests.*#

Les espaces ont été remplacés par le caractère ``_``.

|===
|*Chaînes de caractères de tests*|*Résultats*
|``''`` (vide)|Test passed
|``'06___07_65_19_70_'``|Test passed
|``'666,_the_number_of_the_beast'``|Test passed
|``'Cou_cou\__J_M__B'``|Test passed
|``'_'``|Test passed
|``'__'``|Test passed
|===


===== Lisibilité
[.text-justify]
La lisibilité est la facilité à lire et comprendre ce que le programme fait. Pour cela certains critères vont être pris en compte comme l'aération du code, le nom des variables, les commentaires, la documentation, etc.

|===
|*Points positifs*|*Points négatifs*
|[green]#✔️# Décomposition (aération) du code|[red]#❌# Manque de documentation (javadoc)
|[green]#✔️# Utilisation de méthodes facilement compréhensibles (``for``, ``ArrayList``, ``StringBuilder``)|[red]#❌# Manque de commentaires explicatifs
||[red]#❌# Noms de variables implicites (``temp``, ``temp1``)
|===


===== Qualité
L'outil en ligne Codacy a noté ce programme [yellow]#*D*#. Cela est principalement dû à la mauvaise utilisation de certaines clauses en java.

|===
|*Impacts*|*Points relevés par Codacy*
|[yellow]#Moyen#|Éviter les déclarations vides dans les clauses ``if`` et ``else if``
|[yellow]#Moyen#|Éviter de réassigner les paramètres de la fonction
|===


*TOCONTINUE*



== Catégorie EFFICACITÉ

=== Efficacité n°29 (java)

*NOTATION*
|===
|*5* points|*_Meilleur algorithme* de la catégorie (le plus rapide et passant tous les tests)._
|===

[.text-justify]
Cet algorithme présente une efficacité satisfaisante en traitant tous les cas, avec des temps d'exécution rapides et une complexité qualifiable de linéaire.


==== Prérequis
[.text-justify]
Vérifier la présence du fichier ``efficacite29.java`` dans le répertoire ``~/src/analyse/solutions``. +
 +

[.text-justify]
Remplacer la ligne n°7 du fichier ``EraserTest.java`` (celle avec le commentaire "replace this line") du répertoire ``~/src/test/java`` par le code suivant : +

[SOURCE, java]
----
import analyse.solutions.efficacite29;
----

[.text-justify]
Et remplacer toutes les notations ``Eraser`` du fichier par ``efficacite29``.

[.text-jutify]
Ce programme permet de vérifier que le programme traite bien tous les cas donnés. +
 +

[.text-justify]
Le fichier ``testAnalyse.java`` du répertoire ``~/src/analyse`` permet d'obtenir les temps d'exécution du programme en fonction de chaînes générées aléatoirement de tailles données.


==== Reproductibilité
[.text-justify]
Lancer le code de ``EraserTest.java``et vérifier que le programme traite tous les cas donnés.

[.text-justify]
Lancer le code de ``testAnalyse.java`` et analyser les temps d'exécution en fonction des différentes tailles des chaînes de caractères pour la partie "TEST DU PROGRAMME efficacite29".


==== Analyse de l'Efficacité
[.text-justify]
L'efficacité d'un programme peut se déterminer en fonction de sa complexité et de son temps d'exécution pour différents cas le concernant (des chaînes de caractères de tailles différentes dans le cadre du problème donné pour cette SAE).

===== Tests
[.text-justify]
[green]#*Ce programme passe tous les tests.*#

Les espaces ont été remplacés par le caractère ``_``.

|===
|*Chaînes de caractères de tests*|*Résultats*
|``''`` (vide)|Test passed
|``'06___07_65_19_70_'``|Test passed
|``'666,_the_number_of_the_beast'``|Test passed
|``'Cou_cou\__J_M__B'``|Test passed
|``'_'``|Test passed
|``'__'``|Test passed
|===


===== Temps d'exécution
[.text-justify]
Les temps d'exécution analysés via le programme ``testAnalyse.py`` (en milli-secondes) semblent être inconstants et dépendent surtout du nombre et du placement des espaces contenus dans les chaînes de caractère données. _Cependant, on remarque comme phénomène particulier, que le programme à tendance à prend plus de temps lorsque la chaîne se limite à seulement 1 caractère._

|===
|*Tailles des chaînes*|*Temps d'exécution*
|1 caractères|~1.2 ms
|10 caractères|~0.05 ms
|100 caractères|~0.2 ms
|1000 caractères|~1 ms
|===


===== Complexité
La complexité du programme ``efficacite29.java`` semble se rapprocher de *O(kn)* (avec k étant un nombre réel), les temps d'exécution évoluant de manière linéaire en fonction de la taille des chaînes données. Déterminer une complexité plus précise nécessiterait d'autres paramètres comme le nombre d'espace dans la chaîne ainsi que leur disposition.


{empty} +

=== Efficacité n°135 (java)

*NOTATION*
|===
|*4* points|*_2nd meilleur algorithme* de la catégorie (rapide et passant tous les tests)_
|===

[.text-justify]
Cet algorithme présente une efficacité satisfaisante en traitant tous les cas, avec des temps d'exécution rapides et une complexité qualifiable de linéaire. *TODO*


==== Prérequis
[.text-justify]
Vérifier la présence du fichier ``efficacite135.java`` dans le répertoire ``~/src/analyse/solutions``. +
 +

[.text-justify]
Remplacer la ligne n°7 du fichier ``EraserTest.java`` (celle avec le commentaire "replace this line") du répertoire ``~/src/test/java`` par le code suivant : +

[SOURCE, java]
----
import analyse.solutions.efficacite135;
----

[.text-justify]
Et remplacer toutes les notations ``Eraser`` du fichier par ``efficacite135``.

[.text-jutify]
Ce programme permet de vérifier que le programme traite bien tous les cas donnés. +
 +

[.text-justify]
Le fichier ``testAnalyse.java`` du répertoire ``~/src/analyse`` permet d'obtenir les temps d'exécution du programme en fonction de chaînes générées aléatoirement de tailles données.


==== Reproductibilité
[.text-justify]
Lancer le code de ``EraserTest.java``et vérifier que le programme traite tous les cas donnés.

[.text-justify]
Lancer le code de ``testAnalyse.java`` et analyser les temps d'exécution en fonction des différentes tailles des chaînes de caractères pour la partie "TEST DU PROGRAMME efficacite135".


==== Analyse de l'Efficacité
[.text-justify]
L'efficacité d'un programme peut se déterminer en fonction de sa complexité et de son temps d'exécution pour différents cas le concernant (des chaînes de caractères de tailles différentes dans le cadre du problème donné pour cette SAE).

===== Tests
[.text-justify]
[green]#*Ce programme passe tous les tests.*#

Les espaces ont été remplacés par le caractère ``_``.

|===
|*Chaînes de caractères de tests*|*Résultats*
|``''`` (vide)|Test passed
|``'06___07_65_19_70_'``|Test passed
|``'666,_the_number_of_the_beast'``|Test passed
|``'Cou_cou\__J_M__B'``|Test passed
|``'_'``|Test passed
|``'__'``|Test passed
|===


===== Temps d'exécution
[.text-justify]
Les temps d'exécution analysés via le programme ``testAnalyse.py`` (en milli-secondes) semblent être inconstants et dépendent surtout du nombre et du placement des espaces contenus dans les chaînes de caractère données. _Cependant, on remarque comme phénomène particulier, que le programme à tendance à prend plus de temps lorsque la chaîne se limite à 10 caractères._

|===
|*Tailles des chaînes*|*Temps d'exécution*
|1 caractères|~0.5 ms
|10 caractères|~10 ms
|100 caractères|~0.5 ms
|1000 caractères|~2 ms
|===


===== Complexité
La complexité du programme ``efficacite135.java`` semble se rapprocher de *O(kn)* (avec k étant un nombre réel), les temps d'exécution évoluant de manière linéaire en fonction de la taille des chaînes données. Déterminer une complexité plus précise nécessiterait d'autres paramètres comme le nombre d'espace dans la chaîne ainsi que leur disposition.


{empty} +

=== Efficacité n°21 (python)

*NOTATION*
|===
|[.line-through]#*1* point#|_L'algo ne passe pas tous les tests fournis._
|*3* points|*_3e meilleur algorithme* de la catégorie (rapide)._
|===

[.text-justify]
Cet algorithme ne peut être réellement qualifié d'efficace car ne traitant pas tous les cas possibles de chaînes de caractères. Mais il présente tout de même une efficacité "partielle" plutôt satisfaisante avec des temps d'exécution assez rapides et une complexité qualifiable de sous-quadratique.


==== Prérequis
[.text-justify]
Vérifier la présence du fichier ``efficacite21.py`` dans le répertoire ``~/analyse/solutions``. +
 +

[.text-justify]
Remplacer les premières ligne du fichier ``test.py`` (juste au-dessus de du commentaire "Past above") par le code suivant : +

[SOURCE, python]
----
import sys
sys.path.append('analyse/solutions/') # import python files from path 'analyse/solutions'
from efficacite21 import erase
----

[.text-jutify]
Il permet de vérifier que le programme traite bien tous les cas donnés. +
 +

[.text-justify]
Le fichier ``testAnalyse.py`` du répertoire ``~/analyse`` permet d'obtenir les temps d'exécution du programme en fonction de chaînes générées aléatoirement de tailles données.


==== Reproductibilité
[.text-justify]
Lancer le code de ``test.py``, le programme devrait s'exécuter même si une erreur de compilation est relevée dans la close donnée dans les prérequis. Vérifier que le programme traite tous les cas donnés.

[.text-justify]
Lancer le code de ``testAnalyse.py``, le programme devrait s'exécuter même si une erreur de compilation est relevée. Analyser les temps d'exécution en fonction des différentes tailles des chaînes de caractères pour la partie "TEST DU PROGRAMME efficacite21".


==== Analyse de l'efficacité
[.text-justify]
L'efficacité d'un programme peut se déterminer en fonction de sa complexité et de son temps d'exécution pour différents cas le concernant (des chaînes de caractères de tailles différentes dans le cadre du problème donné pour cette SAE).

===== Tests
[.text-justify]
[red]#*Ce programme ne passe pas tous les tests !*#

Les espaces ont été remplacés par le caractère ``_``.

|===
|*Chaînes de caractères de tests*|*Résultats*
|``''`` (vide)|Test passed
|``'06___07_65_19_70_'``|[red]#❌# ``'06\__07651970' should equal '06___07651970'``
|``'666,_the_number_of_the_beast'``|Test passed
|``'Cou_cou\__J_M__B'``|Test passed
|``'_'``|Test passed
|``'__'``|Test passed
|===


===== Temps d'exécution
[.text-justify]
Les temps d'exécution analysés via le programme ``testAnalyse.py`` (en milli-secondes) semblent être inconstants et dépendent surtout du nombre et du placement des espaces contenus dans les chaînes de caractère données.

|===
|*Tailles des chaînes*|*Temps d'exécution*
|1 caractères|~0.05 ms
|10 caractères|~0.05 ms
|100 caractères|~0.5 ms
|1000 caractères|~5 ms
|===


===== Complexité
La complexité du programme ``efficacite21.py`` semble se rapprocher de *O(nlog(n))* car les ordres de grandeur des temps d'exécution dépendendent de ceux des tailles des chaînes données. Déterminer une complexité plus précise nécessiterait d'autres paramètres comme le nombre d'espace dans la chaîne ainsi que leur disposition.


{empty} +

=== Efficacité n°46 (python)

*NOTATION*
|===
|[.line-through]#*1* point#|_L'algo ne passe pas tous les tests fournis._
|*2* points|*_4e (et dernier) meilleur algorithme* de la catégorie (rapide)._
|===

[.text-justify]
Cet algorithme ne peut être réellement qualifié d'efficace car ne traitant pas tous les cas possibles de chaînes de caractères. Mais il présente tout de même une efficacité "partielle" plutôt satisfaisante avec des temps d'exécution assez rapides et une complexité qualifiable de sous-quadratique.


==== Prérequis
[.text-justify]
Vérifier la présence du fichier ``efficacite46.py`` dans le répertoire ``~/analyse/solutions`` et remplacer le nom de la fonction ``erase2`` à la ligne 2 par ``erase`` pour faciliter la suite des tests. +
 +

[.text-justify]
Remplacer les premières ligne du fichier ``test.py`` (juste au-dessus de du commentaire "Past above") par le code suivant : +

[SOURCE, python]
----
import sys
sys.path.append('analyse/solutions/') # import python files from path 'analyse/solutions'
from efficacite46 import erase
----

[.text-jutify]
Il permet de vérifier que le programme traite bien tous les cas donnés. +
 +

[.text-justify]
Le fichier ``testAnalyse.py`` du répertoire ``~/analyse`` permet d'obtenir les temps d'exécution du programme en fonction de chaînes générées aléatoirement de tailles données.


==== Reproductibilité
[.text-justify]
Lancer le code de ``test.py``, le programme devrait s'exécuter même si une erreur de compilation est relevée dans la close donnée dans les prérequis. Vérifier que le programme traite tous les cas donnés.

[.text-justify]
Lancer le code de ``testAnalyse.py``, le programme devrait s'exécuter même si une erreur de compilation est relevée. Analyser les temps d'exécution en fonction des différentes tailles des chaînes de caractères pour la partie "TEST DU PROGRAMME efficacite46".


==== Analyse de l'Efficacité
[.text-justify]
L'efficacité d'un programme peut se déterminer en fonction de sa complexité et de son temps d'exécution pour différents cas le concernant (des chaînes de caractères de tailles différentes dans le cadre du problème donné pour cette SAE).

===== Tests
[.text-justify]
[red]#*Ce programme ne passe pas tous les tests !*#

Les espaces ont été remplacés par le caractère ``_``.

|===
|*Chaînes de caractères de tests*|*Résultats*
|``''`` (vide)|Test passed
|``'06___07_65_19_70_'``|Test passed
|``'666,_the_number_of_the_beast'``|Test passed
|``'Cou_cou\__J_M__B'``|Test passed
|``'_'``|Test passed
|``'__'``|[red]#❌# ``'\_' should equal '__'``
|===


===== Temps d'exécution
[.text-justify]
Les temps d'exécution analysés via le programme ``testAnalyse.py`` (en milli-secondes) semblent être inconstants et dépendent surtout du nombre et du placement des espaces contenus dans les chaînes de caractère données.

|===
|*Tailles des chaînes*|*Temps d'exécution*
|1 caractères|~0.05 ms
|10 caractères|~0.1 ms
|100 caractères|~0.5 ms
|1000 caractères|~5 ms
|===


===== Complexité
La complexité du programme ``efficacite46.py`` semble se rapprocher de *O(nlog(n))* car les ordres de grandeur des temps d'exécution dépendendent de ceux des tailles des chaînes données. Déterminer une complexité plus précise nécessiterait d'autres paramètres comme le nombre d'espace dans la chaîne ainsi que leur disposition.



== Catégorie SOBRIÉTÉ NUMÉRIQUE

*TOCONTINUE*
